NUM_OF_NOTE_VALUES=128 # 128 possible note values in midi
NUM_OF_VELOCITY_VALUES=128 # 128 possible velocity values in midi

NOTE_DURATION_INTERVAL_SIZE=0.125
MIN_NOTE_DURATION=0
MAX_NOTE_DURATION=2 # max 2 seconds
NUM_OF_DURATION_INTERVALS=int(MAX_NOTE_DURATION/NOTE_DURATION_INTERVAL_SIZE) # 16

MODEL_INPUT_SIZE=NUM_OF_NOTE_VALUES + NUM_OF_VELOCITY_VALUES + NUM_OF_DURATION_INTERVALS # 272
MODEL_OUTPUT_SIZE=MODEL_INPUT_SIZE # 272

# Hyper Parameters
SEQUENCE_LENGTH=16
MODEL_HIDDEN_SIZE=512

